# Site
title: HopeCode
email: fe-ca-el@hotmail.com
name: HopeCode
description: Aceita tomar um café e conversar sobre desenvolvimento? Então vamos lá!
meta_description: "Meu primeiro blog onde vou postar coisas que considero importantes."
theme_name: HopeCode

author: 'Fernando Moreira'

paginate: 15

baseurl: /blog/
url: "http://ihfernando.github.io/blog"

# Social Media
twitter_username:  ihfernando
github_username:   ihfernando
linkedin_username: ihfeeh
behance_username:  ihfernando

# Build
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

# Google services
google_analytics: UA-93790137-1
